import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NavPage from "../component/navBar/page";
import Providers from "../component/utils/provider";

import ThemeHandler from "../component/utils/themeProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
       
        <Providers>
          <NavPage/>
        <ThemeHandler>
          {children}
        </ThemeHandler>
        </Providers>
        
      </body>
    </html>
  );
}
